# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import post_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=155, validators=[post_app.models.validate_content]),
        ),
    ]
