# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_auto_20180330_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated']},
        ),
    ]
